USE fictionalStudents;
GO
ALTER TABLE Student WITH CHECK
ADD CONSTRAINT FK_MajorCode FOREIGN KEY (MajorCode) REFERENCES Major(MajorCode)
ON UPDATE CASCADE
ALTER TABLE Major WITH CHECK
ADD CONSTRAINT FK_Area FOREIGN KEY (Area) REFERENCES Area(AreaCode)
ON UPDATE CASCADE
GO
ALTER TABLE Advisor WITH CHECK
ADD CONSTRAINT FK_Student_Advisor FOREIGN KEY (StudentID) REFERENCES Student(StudentID)
ON UPDATE NO ACTION
GO
ALTER TABLE Grade WITH CHECK
ADD CONSTRAINT FK_Student_Grade FOREIGN KEY(StudentID) REFERENCES Student(StudentID)
ON UPDATE CASCADE;
